name: Test, lint and format

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache pub deps
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.38.5

      - name: Get Flutter packages
        run: flutter pub get

      - name: Flutter lint
        run: flutter analyze --no-pub --no-fatal-infos

      - name: Flutter format
        run: dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --coverage

      - name: Setup lcov
        run: sudo apt-get install -y lcov

      - name: Generate coverage report
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/html

      - name: Check minimum coverage
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          MIN=100
          if (( $(echo "$COVERAGE < $MIN" | bc -l) )); then
            echo "Coverage $COVERAGE% is below minimum $MIN%"
            exit 1
          fi
